[pytest]
addopts = -p no:logging
pythonpath = .
markers =
    flaky :  mark tests as flaky and allows rerun
    regression : mark test as regression that run on every new release
    parametrize : mark test as parametrize that run on multiple dataset
    smoke : mark test as smoke that check the tests running for a build stability so that it can be continued for remaining test to run