[pytest]
addopts = -p no:logging
pythonpath = .
markers =
    flaky :  mark tests as flaky and allows rerun
    regression : mark test as regression that run on every new release
    parametrize : mark test as parametrize that run on multiple datasets